import { useMemo, useState } from "react";
import {
  getTournamentReport,
  type ReportFilters,
  type ReportType,
} from "../../api/scoring/tournamentApi";

/**
 * Phases 20–23 — the ten tournament reports, as PDFs.
 *
 * Every PDF is generated by the backend from structured DTOs, never from this
 * page. That is deliberate and it is not only about not shipping a headless
 * browser: a report rendered from the screen can only contain what the screen
 * shows, so it silently inherits the statistics tab's twenty-row page. A report
 * of the top twenty batters titled "Batting Statistics" is wrong in a way nobody
 * notices.
 *
 * This component therefore does three things and no more: choose a report,
 * choose the filters that report respects, and hand the bytes to the browser.
 *
 * Mobile: the report list is a single column of full-width rows at every
 * viewport, because a download button that has to be aimed at is worse than one
 * that is simply large. The filter row wraps rather than scrolls.
 */

interface TeamOption {
  publicId: string;
  name: string;
  groupName?: string | null;
}

interface StageOption {
  publicId: string;
  stageName: string;
}

interface Props {
  publicId: string;
  teams: TeamOption[];
  stages: StageOption[];
  /** The fixtures already loaded by the page — the ground list comes from them. */
  fixtures: any[];
  showToast: (msg: string) => void;
  setError: (msg: string) => void;
}

/** The ten reports, in the order the brief lists them. */
const REPORTS: {
  type: ReportType;
  label: string;
  blurb: string;
  icon: string;
  filterable: boolean;
}[] = [
  { type: "summary", label: "Tournament Summary", icon: "🏆", filterable: false,
    blurb: "Status, dates, counts, champion and the headline figures." },
  { type: "fixtures", label: "Fixtures", icon: "📅", filterable: true,
    blurb: "Every fixture, scheduled and played, in round order." },
  { type: "points-table", label: "Points Table", icon: "📊", filterable: false,
    blurb: "Standings with net run rate, exactly as the API computes it." },
  { type: "results", label: "Results", icon: "✅", filterable: true,
    blurb: "Completed matches with their recorded result." },
  { type: "team-performance", label: "Team Performance", icon: "👥", filterable: false,
    blurb: "Played, won, lost, totals, highest and lowest, per team." },
  { type: "batting", label: "Batting", icon: "🏏", filterable: false,
    blurb: "Runs, average, strike rate, fifties and hundreds." },
  { type: "bowling", label: "Bowling", icon: "🎯", filterable: false,
    blurb: "Overs, wickets, economy and best figures." },
  { type: "fielding", label: "Fielding", icon: "🧤", filterable: false,
    blurb: "Catches, run-outs, stumpings and total dismissals." },
  { type: "awards", label: "Awards", icon: "🥇", filterable: false,
    blurb: "Every award given, with the reason recorded." },
  { type: "complete", label: "Complete Tournament Report", icon: "📄", filterable: true,
    blurb: "Everything above, in one document." },
];

const STATUSES = ["SCHEDULED", "IN_PROGRESS", "COMPLETED", "CANCELLED", "POSTPONED"];

export default function ReportsTab({
  publicId, teams, stages, fixtures, showToast, setError,
}: Props) {
  const [filters, setFilters] = useState<ReportFilters>({});
  const [busy, setBusy] = useState<ReportType | null>(null);

  /**
   * Grounds come from the fixtures already in hand rather than from a second
   * request: the Venues tab loads the pool lazily, and a filter that is empty
   * until an unrelated tab has been visited is a bug waiting to be reported.
   */
  const grounds = useMemo(() => {
    const seen = new Map<string, string>();
    for (const f of fixtures ?? []) {
      const v = f?.tournamentVenue;
      if (v?.publicId && !seen.has(v.publicId)) seen.set(v.publicId, v.name ?? v.publicId);
    }
    return [...seen.entries()].map(([publicId, name]) => ({ publicId, name }));
  }, [fixtures]);

  const groups = useMemo(() => {
    const seen = new Set<string>();
    for (const t of teams ?? []) if (t.groupName) seen.add(t.groupName);
    return [...seen].sort();
  }, [teams]);

  const activeFilters = Object.values(filters).filter(
    (v) => v !== undefined && String(v).trim() !== "",
  ).length;

  const set = (key: keyof ReportFilters, value: string) =>
    setFilters((f) => ({ ...f, [key]: value || undefined }));

  const download = async (type: ReportType, filterable: boolean) => {
    setBusy(type);
    setError("");
    try {
      // A report with no fixture or result section has no ground and no round,
      // so sending filters would be a lie about what the document respects.
      const blob = await getTournamentReport(publicId, type, filterable ? filters : {});
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `tournament-${type}-${publicId}.pdf`;
      link.click();
      window.URL.revokeObjectURL(url);
      showToast("Report downloaded");
    } catch {
      setError("Could not generate that report. Please try again.");
    } finally {
      setBusy(null);
    }
  };

  return (
    <div data-testid="tournament-panel-reports" className="space-y-4">
      {/* ── FILTERS (Phase 22) ──
          Applied by the server to the fixtures and results sections, and printed
          into the PDF itself — a filtered export that does not say it is
          filtered cannot be told from a tournament that has played four matches. */}
      <div
        data-testid="report-filters"
        className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-3 space-y-2"
      >
        <div className="flex items-center justify-between">
          <div className="text-[10px] font-semibold text-gray-400 uppercase tracking-wide">
            Filters — fixtures, results and the complete report
          </div>
          {activeFilters > 0 && (
            <button
              type="button"
              data-testid="report-filters-clear"
              onClick={() => setFilters({})}
              className="text-xs font-medium px-2.5 py-1 rounded-lg bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-200"
            >
              Clear {activeFilters}
            </button>
          )}
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-2">
          <Select
            testId="report-filter-status" label="Status"
            value={filters.status ?? ""} onChange={(v) => set("status", v)}
            options={STATUSES.map((s) => ({ value: s, label: s.replace("_", " ") }))}
          />
          <Select
            testId="report-filter-stage" label="Stage"
            value={filters.stagePublicId ?? ""} onChange={(v) => set("stagePublicId", v)}
            options={(stages ?? []).map((s) => ({ value: s.publicId, label: s.stageName }))}
          />
          <Select
            testId="report-filter-group" label="Group"
            value={filters.groupName ?? ""} onChange={(v) => set("groupName", v)}
            options={groups.map((g) => ({ value: g, label: g }))}
          />
          <Select
            testId="report-filter-team" label="Team"
            value={filters.teamPublicId ?? ""} onChange={(v) => set("teamPublicId", v)}
            options={(teams ?? []).map((t) => ({ value: t.publicId, label: t.name }))}
          />
          <Select
            testId="report-filter-venue" label="Ground"
            value={filters.venuePublicId ?? ""} onChange={(v) => set("venuePublicId", v)}
            options={grounds.map((g) => ({ value: g.publicId, label: g.name }))}
          />
        </div>
      </div>

      {/* ── THE TEN REPORTS ── */}
      <div className="space-y-2">
        {REPORTS.map((r) => (
          <div
            key={r.type}
            data-testid={`report-row-${r.type}`}
            className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-3 flex items-center gap-3"
          >
            <div className="text-xl flex-shrink-0" aria-hidden="true">{r.icon}</div>
            <div className="min-w-0 flex-1">
              <div className="text-sm font-semibold text-gray-900 dark:text-white truncate">
                {r.label}
              </div>
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
                {r.blurb}
                {r.filterable && activeFilters > 0 && (
                  <span
                    data-testid={`report-row-${r.type}-filtered`}
                    className="ml-1 font-medium text-amber-600 dark:text-amber-400"
                  >
                    · {activeFilters} filter{activeFilters > 1 ? "s" : ""} applied
                  </span>
                )}
              </p>
            </div>
            <button
              type="button"
              data-testid={`report-download-${r.type}`}
              disabled={busy !== null}
              onClick={() => download(r.type, r.filterable)}
              className="flex-shrink-0 px-3 py-2 rounded-xl text-xs font-semibold bg-blue-600 text-white disabled:opacity-50"
            >
              {busy === r.type ? "Preparing…" : "PDF"}
            </button>
          </div>
        ))}
      </div>

      <p className="text-[11px] text-gray-400 px-1">
        Reports are generated on the server from the tournament's own figures, so
        they always match the Points Table and Statistics tabs.
      </p>
    </div>
  );
}

/**
 * A labelled select with a solid background in both themes.
 *
 * engineering-standards.md: border-only controls with no fill are a recurring
 * bug in this codebase, and the Button.tsx secondary-variant incident affected
 * seventeen call sites. This one is filled.
 */
function Select({
  testId, label, value, onChange, options,
}: {
  testId: string;
  label: string;
  value: string;
  onChange: (v: string) => void;
  options: { value: string; label: string }[];
}) {
  return (
    <label className="block">
      <span className="block text-[10px] font-medium text-gray-500 dark:text-gray-400 mb-0.5">
        {label}
      </span>
      <select
        data-testid={testId}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="w-full text-xs rounded-lg px-2 py-1.5 bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-white border border-gray-200 dark:border-gray-700"
      >
        <option value="">All</option>
        {options.map((o) => (
          <option key={o.value} value={o.value}>{o.label}</option>
        ))}
      </select>
    </label>
  );
}
